############################
# Vagrantfile for generic Docker host Jenkins slave
# From https://github.com/phusion/open-vagrant-boxes#using-these-boxes-in-vagrant
############################

def master_env(properties_filename = "../master/example.env")
  properties = {}
  File.open(properties_filename, 'r') do |properties_file|
    properties_file.read.each_line do |line|
      line.strip!
      if (line[0] != ?# and line[0] != ?=)
        i = line.index('=')
        if (i)
          properties[line[0..i - 1].strip] = line[i + 1..-1].strip
        else
          properties[line] = ''
        end
      end
    end
  end
  properties
end

Vagrant.configure(2) do |config|
  swarm_host = `docker-machine ip default`.chomp
  user = master_env['JENKINS_ADMIN_USER']
  pass = master_env['JENKINS_ADMIN_PASSWORD']

  config.vm.box = "phusion/ubuntu-14.04-amd64"

  # Only run the docker provisioning on the first 'vagrant up'
  if Dir.glob("#{File.dirname(__FILE__)}/.vagrant/machines/default/*/id").empty?

    # Install Docker
    pkg_cmd = "wget -q -O - https://get.docker.io/gpg | apt-key add -;" \
      "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list;" \
      "apt-get update -qq; apt-get install -q -y --force-yes lxc-docker openjdk-7-jdk; "

    # Add vagrant user to the docker group
    pkg_cmd << "usermod -a -G docker vagrant; "

    # Download swarm-client
    pkg_cmd << "JENKINS_SWARM_VERSION=2.0;" \
    "curl --create-dirs -sSLo /usr/share/jenkins/swarm-client-$JENKINS_SWARM_VERSION-jar-with-dependencies.jar http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/$JENKINS_SWARM_VERSION/swarm-client-$JENKINS_SWARM_VERSION-jar-with-dependencies.jar" \
    " && chmod 755 /usr/share/jenkins"

    config.vm.provision :shell, :inline => pkg_cmd

  end

  # Always attempt to register the slave on 'vagrant up'
  config.vm.provision :shell, :inline => <<-SCRIPT
    JAR=`ls -1 /usr/share/jenkins/swarm-client-*.jar | tail -n 1`
    CMD="$JAVA_OPTS -jar $JAR -fsroot $HOME -master http://#{swarm_host}:8080 -username #{user} -password #{pass} -labels docker"
    echo "Running command: java $CMD"
    java $CMD
  SCRIPT
  # TODO: run `java InstallCert #{swarm_host}`
  # Based on http://stackoverflow.com/a/1828832
end
